"""test the test

Revision ID: a880b445add1
Revises: ae8e12262aea
Create Date: 2024-11-25 12:25:41.216713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a880b445add1'
down_revision = 'ae8e12262aea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gamemasters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gamemasters', schema=None) as batch_op:
        batch_op.drop_column('test')

    # ### end Alembic commands ###
