"""seeeding

Revision ID: ae8e12262aea
Revises: 
Create Date: 2024-11-25 12:24:06.656737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae8e12262aea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('character_class', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gamemasters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('gamemaster_id', sa.Integer(), nullable=True),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name=op.f('fk_players_character_id_characters')),
    sa.ForeignKeyConstraint(['gamemaster_id'], ['gamemasters.id'], name=op.f('fk_players_gamemaster_id_gamemasters')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session_players',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('is_in_session', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_session_players_player_id_players')),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_session_players_session_id_sessions')),
    sa.PrimaryKeyConstraint('session_id', 'player_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session_players')
    op.drop_table('players')
    op.drop_table('sessions')
    op.drop_table('gamemasters')
    op.drop_table('characters')
    # ### end Alembic commands ###
